name = "BinaryFields"
uuid = "0fee9d7f-8397-4f0d-9ec6-117db1666467"
authors = ["angeris <guille@angeris.net>", "Andrija <akinovak@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
Random = "1.11.0"
SIMD = "3.7.1"
