name = "MultilinearPoly"
uuid = "738c1076-b784-4255-a602-5a9e144980bc"
authors = ["Andrija <akinovak@gmail.com>"]
version = "0.1.0"

[deps]
BinaryFields = "0fee9d7f-8397-4f0d-9ec6-117db1666467"

[compat]
BinaryFields = "0.1.0"
